---
version: "{build}"

clone_folder: c:\gopath\src\github.com\exercism\cli

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

init:
  - git config --global core.autocrlf input

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build_script:
  - go test -cover ./...
